# Generated by Django 3.0.2 on 2022-05-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0003_auto_20220520_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reply',
            field=models.IntegerField(default=0, verbose_name='답글위치'),
        ),
    ]
