# Generated by Django 3.0.2 on 2022-05-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0004_comment_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='comments',
            field=models.PositiveIntegerField(null=True, verbose_name='댓글수'),
        ),
        migrations.AddField(
            model_name='board',
            name='hits',
            field=models.PositiveIntegerField(default=0, verbose_name='조회수'),
        ),
    ]
