# Generated by Django 3.0.2 on 2022-05-20 13:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0005_auto_20220520_1307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'verbose_name': '자유게시판', 'verbose_name_plural': '자유게시판'},
        ),
        migrations.RemoveField(
            model_name='board',
            name='created_date',
        ),
        migrations.AddField(
            model_name='board',
            name='registered_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='등록시간'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='board',
            table='자유게시판',
        ),
    ]
