# Generated by Django 3.0.2 on 2022-05-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0006_auto_20220520_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='reply',
            field=models.IntegerField(default=0, null=True, verbose_name='답글위치'),
        ),
    ]
